### ISSUE TITLE
NetStandard 2.0 support - checklist

### ISSUE THREAD

**Issue by alex-bogomaz** [SuaveIO/suave#677]
Since Suave is moving to NetStandard 2.0 support, 
lets track what is still needed:

- [x] restore Suave APIs that were removed for NetStandard 1.6, but can work under NetStandard 2.0
- [x] clean-up code from ```#if NETSTANDARD1_5``` etc...
- [x] run NetCore tests for "standard TCP engine" under Linux
- [x] run NetCore tests under MacOS
- [x] use NetCore "Http.fs"
- [x] port all relevant examples to NetCore
- [x] do not use ```<TargetFramework>netstandard2.0</TargetFramework>``` in "Examples" - now it is not possible to ```dotnet run``` "Example" and "Pong". Target ```netcoreapp2.0``` instead.

Please add what is missing.

**Comment by ademar** [comment]
Cool, would you mind sending a PR for these ?

**Comment by alex-bogomaz** [comment]
sure.. after holidays :-)

**Comment by ademar** [comment]
OK, I'll give it a try later today.

**Comment by haf** [comment]
@alex-bogomaz I've upgraded Http.fs now

But I can't release it, because this PR/v2.3.0 of Suave has a very recent FSharp.Core constraint:

https://gist.github.com/haf/f2cf4557e4765e8cca6a18dbcaaf4a14

Can you help me?

**Comment by haf** [comment]
@ademar The [above](https://github.com/SuaveIO/suave/issues/677#issuecomment-356628277) is a good reason not to release the beta just yet.

**Comment by haf** [comment]
PIng

**Comment by ademar** [comment]
Suave does not depend on Http.fs, I am not sure why is that important.

**Comment by haf** [comment]
I mean; why does Suave have to depend on the *very latest* F#?

**Comment by alex-bogomaz** [comment]
this PR https://github.com/SuaveIO/suave/pull/685 should force version "4.1.18" of "FSharp.Core" for NetStandard 2.0 Suave nugets

**Comment by haf** [comment]
#685 merged

**Comment by alex-bogomaz** [comment]
Hi - there are 2 things that could be discussed in scope of NetStandard 2.0 support:

1) PR https://github.com/SuaveIO/suave/pull/687 - using latest "FSharp.Core" for test project. This fixes cookie serialization issues related to NetStandard 1.6 "FSharp.Core".

2) PR https://github.com/SuaveIO/suave/pull/688 - more correct reusing of same address (similar to what they did for Kestrel) + adding OSX to CI.

**Comment by haf** [comment]
v5 released https://www.nuget.org/packages/Http.fs/

**Comment by aaron-comyn** [comment]
Minor issue on an example upgrade: SignalRDemo.netcore.fsproj compiles but fails during execution (''Could not load type 'System.Security.Cryptography.DpapiDataProtector' from assembly 'System.Security'").  AFAIK that class requires the full .NET framework.  

AspnetCore.SignalR is in preview now, and seemingly relis on IApplicationBuilder.  Suave.AspNetCore can likely bridge the gap, though I prefer Suave by itself.

[ Awesome job on the updgrade so far, btw, Suave is looking as pretty as ever :D ]
